import { WizardData } from "@/lib/schemas"

export const mapFichaToWizardData = (ficha: any, encuestadorDoc: string, encuestadorPerfil: string): WizardData => {
  return {
    estadoVisita: String(ficha.estadoVisita || '1'),
    observacionesRechazo: ficha.observacionesRechazo || '',
    departamento: ficha.departamento || 'RISARALDA',
    municipio: ficha.municipio || 'PEREIRA',
    centroPoblado: ficha.centroPoblado || '',
    descripcionUbicacion: ficha.descripcionUbicacion || '',
    uzpe: ficha.uzpe || '',
    microterritorio: ficha.microterritorio || '',
    direccion: ficha.direccion || '',
    latitud: ficha.latitud ? String(ficha.latitud) : undefined,
    longitud: ficha.longitud ? String(ficha.longitud) : undefined,
    fechaDiligenciamiento: (() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` })(),
    numEBS: ficha.numEBS || '',
    prestadorPrimario: ficha.prestadorPrimario || '',
    
    // Todo lo nuevo del Excel/BD
    numHogar: ficha.numHogar || '',
    numFamilia: ficha.numFamilia || '',
    codFicha: ficha.codFicha || '',
    tipoDocEncuestador: 'CC',
    numDocEncuestador: encuestadorDoc,
    perfilEncuestador: encuestadorPerfil,

    tipoVivienda: ficha.tipoVivienda ? String(ficha.tipoVivienda) : '',
    tipoViviendaDesc: ficha.tipoViviendaDesc || '',
    matParedes: ficha.matParedes ? String(ficha.matParedes) : '',
    matPisos: ficha.matPisos ? String(ficha.matPisos) : '',
    matTechos: ficha.matTechos ? String(ficha.matTechos) : '',
    numHogares: ficha.numHogares ? String(ficha.numHogares) : '',
    numDormitorios: ficha.numDormitorios ? String(ficha.numDormitorios) : '',
    estratoSocial: ficha.estratoSocial ? String(ficha.estratoSocial) : '',
    hacinamiento: !!ficha.hacinamiento,
    fuenteAgua: Array.isArray(ficha.fuenteAgua) ? ficha.fuenteAgua.map(String) : [],
    dispExcretas: Array.isArray(ficha.dispExcretas) ? ficha.dispExcretas.map(String) : [],
    aguasResiduales: Array.isArray(ficha.aguasResiduales) ? ficha.aguasResiduales.map(String) : [],
    dispResiduos: Array.isArray(ficha.dispResiduos) ? ficha.dispResiduos.map(String) : [],
    riesgoAccidente: Array.isArray(ficha.riesgoAccidente) ? ficha.riesgoAccidente.map(String) : [],
    fuenteEnergia: ficha.fuenteEnergia ? String(ficha.fuenteEnergia) : '',
    presenciaVectores: ficha.presenciaVectores === true || String(ficha.presenciaVectores) === 'true' ? 'true' : 'false',
    animales: Array.isArray(ficha.animales) ? ficha.animales.map(String) : [],
    cantAnimales: ficha.cantAnimales ? String(ficha.cantAnimales) : '',
    vacunacionMascotas: !!ficha.vacunacionMascotas,

    // Familia (Step 3)
    tipoFamilia: ficha.tipoFamilia ? String(ficha.tipoFamilia) : '',
    numIntegrantes: ficha.numIntegrantes ? String(ficha.numIntegrantes) : '0',
    apgar: ficha.apgar ? String(ficha.apgar) : '',
    apgarRespuestas: Array.isArray(ficha.apgarRespuestas) ? ficha.apgarRespuestas : [],
    ecomapa: ficha.ecomapa ? String(ficha.ecomapa) : '',
    cuidadorPrincipal: ficha.cuidadorPrincipal ? true : false,
    zarit: ficha.zarit ? String(ficha.zarit) : '',
    vulnerabilidades: Array.isArray(ficha.vulnerabilidades) ? ficha.vulnerabilidades.map(String) : [],

    // Integrantes (Step 4, 5)
    integrantes: (ficha.pacientes || []).map((p: any) => ({
      id: p.id,
      primerNombre: p.nombres?.split(' ')[0] || '',
      segundoNombre: p.nombres?.split(' ').slice(1).join(' ') || '',
      primerApellido: p.apellidos?.split(' ')[0] || '',
      segundoApellido: p.apellidos?.split(' ').slice(1).join(' ') || '',
      tipoDoc: "CC", 
      numDoc: p.documento || '',
      fechaNacimiento: p.fechaNacimiento || '',
      sexo: p.sexo ? String(p.sexo) : '',
      gestante: String(p.gestante || 'NA'),
      mesesGestacion: p.mesesGestacion ? String(p.mesesGestacion) : '',
      telefono: p.telefono || '',
      estadoCivil: p.estadoCivil ? String(p.estadoCivil) : '',
      parentesco: p.parentesco ? String(p.parentesco) : p.rolFamilia ? String(p.rolFamilia) : '',
      
      padreId: p.padreId || '',
      madreId: p.madreId || '',
      parejaId: p.parejaId || '',
      tipoPareja: p.tipoPareja || '',
      tipoHijo: p.tipoHijo || '',
      estadoVital: p.estadoVital || 'VIVO',
      
      nivelEducativo: p.nivelEducativo ? String(p.nivelEducativo) : '',
      ocupacion: p.ocupacion ? String(p.ocupacion) : '',
      regimen: p.regimen ? String(p.regimen) : '',
      eapb: p.eapb || '',
      etnia: p.etnia ? String(p.etnia) : '',
      puebloIndigena: p.puebloIndigena || '',
      grupoPoblacional: Array.isArray(p.grupoPoblacional) ? p.grupoPoblacional.map(String) : [],
      barrerasAcceso: Array.isArray(p.barrerasAcceso) ? p.barrerasAcceso.map(String) : [],
      discapacidades: Array.isArray(p.discapacidades) ? p.discapacidades.map(String) : [],

      antecedentes: p.antecedentes && typeof p.antecedentes === 'object' && !Array.isArray(p.antecedentes) ? p.antecedentes : {},
      antecTransmisibles: p.antecTransmisibles && typeof p.antecTransmisibles === 'object' && !Array.isArray(p.antecTransmisibles) ? p.antecTransmisibles : {},
      peso: p.peso ? String(p.peso) : '',
      talla: p.talla ? String(p.talla) : '',
      perimetroBraquial: p.perimetroBraquial ? String(p.perimetroBraquial) : '',
      diagNutricional: p.diagNutricional ? String(p.diagNutricional) : '',
      practicaDeportiva: !!p.practicaDeportiva,
      lactanciaMaterna: !!p.lactanciaMaterna,
      lactanciaMeses: p.lactanciaMeses ? String(p.lactanciaMeses) : '',
      esquemaAtenciones: !!p.esquemaAtenciones,
      esquemaVacunacion: !!p.esquemaVacunacion,
      intervencionesPendientes: Array.isArray(p.intervencionesPendientes) ? p.intervencionesPendientes.map(String) : [],
      enfermedadAguda: !!p.enfermedadAguda,
      recibeAtencionMedica: !!p.recibeAtencionMedica,
      remisiones: Array.isArray(p.remisiones) ? p.remisiones.map(String) : [],
    })),

    familiogramaCodigo: ficha.familiogramaCodigo || ''
  } as unknown as WizardData
}
