import { WizardData } from "@/lib/schemas"

export const mapFichaToWizardData = (ficha: any, encuestadorDoc: string, encuestadorPerfil: string): WizardData => {
  return {
    estadoVisita: String(ficha.estadoVisita || '1'),
    observacionesRechazo: ficha.observacionesRechazo || '',
    departamento: ficha.departamento || 'RISARALDA',
    municipio: ficha.municipio || 'PEREIRA',
    centroPoblado: ficha.centroPoblado || '',
    descripcionUbicacion: ficha.descripcionUbicacion || '',
    uzpe: ficha.uzpe || '',
    direccion: ficha.direccion || '',
    latitud: ficha.latitud ? String(ficha.latitud) : undefined,
    longitud: ficha.longitud ? String(ficha.longitud) : undefined,
    fechaDiligenciamiento: (() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` })(),
    numEBS: ficha.numEBS || '',
    prestadorPrimario: ficha.prestadorPrimario || '',
    
    // Todo lo nuevo del Excel/BD
    numHogar: ficha.numHogar || '',
    numFamilia: ficha.numFamilia || '',
    codFicha: ficha.codFicha || '',
    tipoDocEncuestador: 'CC',
    numDocEncuestador: encuestadorDoc,
    perfilEncuestador: encuestadorPerfil,

    tipoVivienda: ficha.tipoVivienda ? String(ficha.tipoVivienda) : '',
    tipoViviendaDesc: ficha.tipoViviendaDesc || '',
    matParedes: ficha.matParedes ? String(ficha.matParedes) : '',
    matPisos: ficha.matPisos ? String(ficha.matPisos) : '',
    matTechos: ficha.matTechos ? String(ficha.matTechos) : '',
    numHogares: ficha.numHogares ? String(ficha.numHogares) : '',
    numDormitorios: ficha.numDormitorios ? String(ficha.numDormitorios) : '',
    estratoSocial: ficha.estratoSocial ? String(ficha.estratoSocial) : '',
    hacinamiento: ficha.hacinamiento ? true : false,
    fuenteAgua: ficha.fuenteAgua || [],
    dispExcretas: ficha.dispExcretas || [],
    aguasResiduales: ficha.aguasResiduales || [],
    dispResiduos: ficha.dispResiduos || [],
    riesgoAccidente: ficha.riesgoAccidente || [],
    fuenteEnergia: ficha.fuenteEnergia ? String(ficha.fuenteEnergia) : '',
    presenciaVectores: ficha.presenciaVectores ? true : false,
    animales: ficha.animales || [],
    cantAnimales: ficha.cantAnimales ? String(ficha.cantAnimales) : '',
    vacunacionMascotas: ficha.vacunacionMascotas ? true : false,

    // Familia (Step 3)
    tipoFamilia: ficha.tipoFamilia ? String(ficha.tipoFamilia) : '',
    numIntegrantes: ficha.numIntegrantes ? String(ficha.numIntegrantes) : '0',
    apgar: ficha.apgar ? String(ficha.apgar) : '',
    ecomapa: ficha.ecomapa ? String(ficha.ecomapa) : '',
    cuidadorPrincipal: ficha.cuidadorPrincipal ? true : false,
    zarit: ficha.zarit ? String(ficha.zarit) : '',
    vulnerabilidades: ficha.vulnerabilidades || [],

    // Integrantes (Step 4, 5)
    integrantes: (ficha.pacientes || []).map((p: any) => ({
      id: p.id,
      primerNombre: p.nombres?.split(' ')[0] || '',
      segundoNombre: p.nombres?.split(' ').slice(1).join(' ') || '',
      primerApellido: p.apellidos?.split(' ')[0] || '',
      segundoApellido: p.apellidos?.split(' ').slice(1).join(' ') || '',
      tipoDoc: "CC", 
      numDoc: p.documento || '',
      fechaNacimiento: p.fechaNacimiento || '',
      sexo: p.sexo ? String(p.sexo) : '',
      gestante: String(p.gestante || 'NA'),
      mesesGestacion: p.mesesGestacion ? String(p.mesesGestacion) : '',
      telefono: p.telefono || '',
      estadoCivil: p.estadoCivil ? String(p.estadoCivil) : '',
      parentesco: p.rolFamilia ? String(p.rolFamilia) : '',
      
      padreId: p.padreId || '',
      madreId: p.madreId || '',
      parejaId: p.parejaId || '',
      tipoPareja: p.tipoPareja || '',
      tipoHijo: p.tipoHijo || '',
      estadoVital: p.estadoVital || 'VIVO',
      
      nivelEducativo: p.nivelEducativo ? String(p.nivelEducativo) : '',
      ocupacion: p.ocupacion ? String(p.ocupacion) : '',
      regimen: p.regimen ? String(p.regimen) : '',
      eapb: p.eapb || '',
      etnia: p.etnia ? String(p.etnia) : '',
      puebloIndigena: p.puebloIndigena || '',
      grupoPoblacional: p.grupoPoblacional || [],
      barrerasAcceso: p.barrerasAcceso || [],
      discapacidades: p.discapacidades || [],

      antecedentes: p.antecedentes || {},
      antecTransmisibles: p.antecTransmisibles || {},
      peso: p.peso ? String(p.peso) : '',
      talla: p.talla ? String(p.talla) : '',
      perimetroBraquial: p.perimetroBraquial ? String(p.perimetroBraquial) : '',
      diagNutricional: p.diagNutricional ? String(p.diagNutricional) : '',
      practicaDeportiva: p.practicaDeportiva ? true : false,
      lactanciaMaterna: p.lactanciaMaterna ? true : false,
      lactanciaMeses: p.lactanciaMeses ? String(p.lactanciaMeses) : '',
      esquemaAtenciones: p.esquemaAtenciones ? true : false,
      intervencionesPendientes: Array.isArray(p.intervencionesPendientes) ? p.intervencionesPendientes.map(String) : [],
      enfermedadAguda: p.enfermedadAguda ? true : false,
      recibeAtencionMedica: p.recibeAtencionMedica ? true : false,
      remisiones: Array.isArray(p.remisiones) ? p.remisiones.map(String) : [],
    })),

    familiogramaCodigo: ficha.familiogramaCodigo || ''
  } as unknown as WizardData
}
